worldName: GurkenTruppe
serverName: GurkenTruppe
password: gurken1234 

resources: {}

image:
  repository: lloesche/valheim-server
  tag: latest

storage:
  kind: hostvol
  hostvol:
    path: /var/data/valheim
  pvc:
    size: 5Gi

serverStorage:
  kind: hostvol
  hostvol:
    path: /var/data/valheim-server
  pvc:
    size: 20Gi

# if useHostNetworking is set to true then no service is created
# and the gamePort 
useHostNetworking: true
# if set to true, the game port will be published as a nodePort
networking:
  # Optional additional annotations to add to the service
  # serviceAnnotations: {}
  # Optional additional labels to add to the service
  # serviceLabels: {}
  serviceType: NodePort
  gamePort: 2456
  publishQueryPort: true
  nodePort: 2456
  externalIPs: [135.181.57.218]


nodeSelector: {}
  
tolerations: {}

# If you utilize priority classes, you can define the priority class for this deployment here
# priorityClassName: my-priority-class-name

resources:
  requests:
    memory: "6Gi"
    cpu: "4000m"

extraEnvironmentVars:
  BACKUPS: true
  BACKUPS_CRON: "0 * * * *"
  BACKUPS_MAX_AGE: 3
  BEPINEX: true
  # POST_BACKUP_HOOK: "timeout 300 scp -i /extraVolumes/backup-ssh-key/ssh-privatekey -o StrictHostKeyChecking=no @BACKUP_FILE@ myself@example.com:~/valheim_backups/$(basename @BACKUP_FILE@)"

# extraVolumes:
# - type: secret
#   name: backup-ssh-key
#   defaultMode: 0600